/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AdminRouteImport } from './routes/_admin'
import { Route as AdminIndexRouteImport } from './routes/_admin/index'
import { Route as AdminUsageRouteImport } from './routes/_admin/usage'
import { Route as AdminSkillsRouteImport } from './routes/_admin/skills'
import { Route as AdminSettingsRouteImport } from './routes/_admin/settings'
import { Route as AdminSessionsRouteImport } from './routes/_admin/sessions'
import { Route as AdminRemindersRouteImport } from './routes/_admin/reminders'
import { Route as AdminModelsRouteImport } from './routes/_admin/models'
import { Route as AdminMemoryRouteImport } from './routes/_admin/memory'
import { Route as AdminLogsRouteImport } from './routes/_admin/logs'
import { Route as AdminDiagnosticsRouteImport } from './routes/_admin/diagnostics'
import { Route as AdminDesignSystemRouteImport } from './routes/_admin/design-system'
import { Route as AdminDebugRouteImport } from './routes/_admin/debug'
import { Route as AdminCronRouteImport } from './routes/_admin/cron'
import { Route as AdminConfigRouteImport } from './routes/_admin/config'
import { Route as AdminChatRouteImport } from './routes/_admin/chat'
import { Route as AdminChannelsRouteImport } from './routes/_admin/channels'
import { Route as AdminApprovalsRouteImport } from './routes/_admin/approvals'
import { Route as AdminAgentsRouteImport } from './routes/_admin/agents'
import { Route as AdminSessionsIdRouteImport } from './routes/_admin/sessions.$id'

const AdminRoute = AdminRouteImport.update({
  id: '/_admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsageRoute = AdminUsageRouteImport.update({
  id: '/usage',
  path: '/usage',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSkillsRoute = AdminSkillsRouteImport.update({
  id: '/skills',
  path: '/skills',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSessionsRoute = AdminSessionsRouteImport.update({
  id: '/sessions',
  path: '/sessions',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRemindersRoute = AdminRemindersRouteImport.update({
  id: '/reminders',
  path: '/reminders',
  getParentRoute: () => AdminRoute,
} as any)
const AdminModelsRoute = AdminModelsRouteImport.update({
  id: '/models',
  path: '/models',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMemoryRoute = AdminMemoryRouteImport.update({
  id: '/memory',
  path: '/memory',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLogsRoute = AdminLogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDiagnosticsRoute = AdminDiagnosticsRouteImport.update({
  id: '/diagnostics',
  path: '/diagnostics',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDesignSystemRoute = AdminDesignSystemRouteImport.update({
  id: '/design-system',
  path: '/design-system',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDebugRoute = AdminDebugRouteImport.update({
  id: '/debug',
  path: '/debug',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCronRoute = AdminCronRouteImport.update({
  id: '/cron',
  path: '/cron',
  getParentRoute: () => AdminRoute,
} as any)
const AdminConfigRoute = AdminConfigRouteImport.update({
  id: '/config',
  path: '/config',
  getParentRoute: () => AdminRoute,
} as any)
const AdminChatRoute = AdminChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => AdminRoute,
} as any)
const AdminChannelsRoute = AdminChannelsRouteImport.update({
  id: '/channels',
  path: '/channels',
  getParentRoute: () => AdminRoute,
} as any)
const AdminApprovalsRoute = AdminApprovalsRouteImport.update({
  id: '/approvals',
  path: '/approvals',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAgentsRoute = AdminAgentsRouteImport.update({
  id: '/agents',
  path: '/agents',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSessionsIdRoute = AdminSessionsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AdminSessionsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AdminIndexRoute
  '/agents': typeof AdminAgentsRoute
  '/approvals': typeof AdminApprovalsRoute
  '/channels': typeof AdminChannelsRoute
  '/chat': typeof AdminChatRoute
  '/config': typeof AdminConfigRoute
  '/cron': typeof AdminCronRoute
  '/debug': typeof AdminDebugRoute
  '/design-system': typeof AdminDesignSystemRoute
  '/diagnostics': typeof AdminDiagnosticsRoute
  '/logs': typeof AdminLogsRoute
  '/memory': typeof AdminMemoryRoute
  '/models': typeof AdminModelsRoute
  '/reminders': typeof AdminRemindersRoute
  '/sessions': typeof AdminSessionsRouteWithChildren
  '/settings': typeof AdminSettingsRoute
  '/skills': typeof AdminSkillsRoute
  '/usage': typeof AdminUsageRoute
  '/sessions/$id': typeof AdminSessionsIdRoute
}
export interface FileRoutesByTo {
  '/agents': typeof AdminAgentsRoute
  '/approvals': typeof AdminApprovalsRoute
  '/channels': typeof AdminChannelsRoute
  '/chat': typeof AdminChatRoute
  '/config': typeof AdminConfigRoute
  '/cron': typeof AdminCronRoute
  '/debug': typeof AdminDebugRoute
  '/design-system': typeof AdminDesignSystemRoute
  '/diagnostics': typeof AdminDiagnosticsRoute
  '/logs': typeof AdminLogsRoute
  '/memory': typeof AdminMemoryRoute
  '/models': typeof AdminModelsRoute
  '/reminders': typeof AdminRemindersRoute
  '/sessions': typeof AdminSessionsRouteWithChildren
  '/settings': typeof AdminSettingsRoute
  '/skills': typeof AdminSkillsRoute
  '/usage': typeof AdminUsageRoute
  '/': typeof AdminIndexRoute
  '/sessions/$id': typeof AdminSessionsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_admin': typeof AdminRouteWithChildren
  '/_admin/agents': typeof AdminAgentsRoute
  '/_admin/approvals': typeof AdminApprovalsRoute
  '/_admin/channels': typeof AdminChannelsRoute
  '/_admin/chat': typeof AdminChatRoute
  '/_admin/config': typeof AdminConfigRoute
  '/_admin/cron': typeof AdminCronRoute
  '/_admin/debug': typeof AdminDebugRoute
  '/_admin/design-system': typeof AdminDesignSystemRoute
  '/_admin/diagnostics': typeof AdminDiagnosticsRoute
  '/_admin/logs': typeof AdminLogsRoute
  '/_admin/memory': typeof AdminMemoryRoute
  '/_admin/models': typeof AdminModelsRoute
  '/_admin/reminders': typeof AdminRemindersRoute
  '/_admin/sessions': typeof AdminSessionsRouteWithChildren
  '/_admin/settings': typeof AdminSettingsRoute
  '/_admin/skills': typeof AdminSkillsRoute
  '/_admin/usage': typeof AdminUsageRoute
  '/_admin/': typeof AdminIndexRoute
  '/_admin/sessions/$id': typeof AdminSessionsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agents'
    | '/approvals'
    | '/channels'
    | '/chat'
    | '/config'
    | '/cron'
    | '/debug'
    | '/design-system'
    | '/diagnostics'
    | '/logs'
    | '/memory'
    | '/models'
    | '/reminders'
    | '/sessions'
    | '/settings'
    | '/skills'
    | '/usage'
    | '/sessions/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/agents'
    | '/approvals'
    | '/channels'
    | '/chat'
    | '/config'
    | '/cron'
    | '/debug'
    | '/design-system'
    | '/diagnostics'
    | '/logs'
    | '/memory'
    | '/models'
    | '/reminders'
    | '/sessions'
    | '/settings'
    | '/skills'
    | '/usage'
    | '/'
    | '/sessions/$id'
  id:
    | '__root__'
    | '/_admin'
    | '/_admin/agents'
    | '/_admin/approvals'
    | '/_admin/channels'
    | '/_admin/chat'
    | '/_admin/config'
    | '/_admin/cron'
    | '/_admin/debug'
    | '/_admin/design-system'
    | '/_admin/diagnostics'
    | '/_admin/logs'
    | '/_admin/memory'
    | '/_admin/models'
    | '/_admin/reminders'
    | '/_admin/sessions'
    | '/_admin/settings'
    | '/_admin/skills'
    | '/_admin/usage'
    | '/_admin/'
    | '/_admin/sessions/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AdminRoute: typeof AdminRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_admin': {
      id: '/_admin'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin/': {
      id: '/_admin/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/usage': {
      id: '/_admin/usage'
      path: '/usage'
      fullPath: '/usage'
      preLoaderRoute: typeof AdminUsageRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/skills': {
      id: '/_admin/skills'
      path: '/skills'
      fullPath: '/skills'
      preLoaderRoute: typeof AdminSkillsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/settings': {
      id: '/_admin/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/sessions': {
      id: '/_admin/sessions'
      path: '/sessions'
      fullPath: '/sessions'
      preLoaderRoute: typeof AdminSessionsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/reminders': {
      id: '/_admin/reminders'
      path: '/reminders'
      fullPath: '/reminders'
      preLoaderRoute: typeof AdminRemindersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/models': {
      id: '/_admin/models'
      path: '/models'
      fullPath: '/models'
      preLoaderRoute: typeof AdminModelsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/memory': {
      id: '/_admin/memory'
      path: '/memory'
      fullPath: '/memory'
      preLoaderRoute: typeof AdminMemoryRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/logs': {
      id: '/_admin/logs'
      path: '/logs'
      fullPath: '/logs'
      preLoaderRoute: typeof AdminLogsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/diagnostics': {
      id: '/_admin/diagnostics'
      path: '/diagnostics'
      fullPath: '/diagnostics'
      preLoaderRoute: typeof AdminDiagnosticsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/design-system': {
      id: '/_admin/design-system'
      path: '/design-system'
      fullPath: '/design-system'
      preLoaderRoute: typeof AdminDesignSystemRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/debug': {
      id: '/_admin/debug'
      path: '/debug'
      fullPath: '/debug'
      preLoaderRoute: typeof AdminDebugRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/cron': {
      id: '/_admin/cron'
      path: '/cron'
      fullPath: '/cron'
      preLoaderRoute: typeof AdminCronRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/config': {
      id: '/_admin/config'
      path: '/config'
      fullPath: '/config'
      preLoaderRoute: typeof AdminConfigRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/chat': {
      id: '/_admin/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof AdminChatRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/channels': {
      id: '/_admin/channels'
      path: '/channels'
      fullPath: '/channels'
      preLoaderRoute: typeof AdminChannelsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/approvals': {
      id: '/_admin/approvals'
      path: '/approvals'
      fullPath: '/approvals'
      preLoaderRoute: typeof AdminApprovalsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/agents': {
      id: '/_admin/agents'
      path: '/agents'
      fullPath: '/agents'
      preLoaderRoute: typeof AdminAgentsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/sessions/$id': {
      id: '/_admin/sessions/$id'
      path: '/$id'
      fullPath: '/sessions/$id'
      preLoaderRoute: typeof AdminSessionsIdRouteImport
      parentRoute: typeof AdminSessionsRoute
    }
  }
}

interface AdminSessionsRouteChildren {
  AdminSessionsIdRoute: typeof AdminSessionsIdRoute
}

const AdminSessionsRouteChildren: AdminSessionsRouteChildren = {
  AdminSessionsIdRoute: AdminSessionsIdRoute,
}

const AdminSessionsRouteWithChildren = AdminSessionsRoute._addFileChildren(
  AdminSessionsRouteChildren,
)

interface AdminRouteChildren {
  AdminAgentsRoute: typeof AdminAgentsRoute
  AdminApprovalsRoute: typeof AdminApprovalsRoute
  AdminChannelsRoute: typeof AdminChannelsRoute
  AdminChatRoute: typeof AdminChatRoute
  AdminConfigRoute: typeof AdminConfigRoute
  AdminCronRoute: typeof AdminCronRoute
  AdminDebugRoute: typeof AdminDebugRoute
  AdminDesignSystemRoute: typeof AdminDesignSystemRoute
  AdminDiagnosticsRoute: typeof AdminDiagnosticsRoute
  AdminLogsRoute: typeof AdminLogsRoute
  AdminMemoryRoute: typeof AdminMemoryRoute
  AdminModelsRoute: typeof AdminModelsRoute
  AdminRemindersRoute: typeof AdminRemindersRoute
  AdminSessionsRoute: typeof AdminSessionsRouteWithChildren
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminSkillsRoute: typeof AdminSkillsRoute
  AdminUsageRoute: typeof AdminUsageRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAgentsRoute: AdminAgentsRoute,
  AdminApprovalsRoute: AdminApprovalsRoute,
  AdminChannelsRoute: AdminChannelsRoute,
  AdminChatRoute: AdminChatRoute,
  AdminConfigRoute: AdminConfigRoute,
  AdminCronRoute: AdminCronRoute,
  AdminDebugRoute: AdminDebugRoute,
  AdminDesignSystemRoute: AdminDesignSystemRoute,
  AdminDiagnosticsRoute: AdminDiagnosticsRoute,
  AdminLogsRoute: AdminLogsRoute,
  AdminMemoryRoute: AdminMemoryRoute,
  AdminModelsRoute: AdminModelsRoute,
  AdminRemindersRoute: AdminRemindersRoute,
  AdminSessionsRoute: AdminSessionsRouteWithChildren,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminSkillsRoute: AdminSkillsRoute,
  AdminUsageRoute: AdminUsageRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AdminRoute: AdminRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
