//! Diesel table definitions.
//!
//! These correspond to the migration SQL and define the compile-time-checked
//! query surface. In a full Diesel workflow these would be auto-generated by
//! `diesel print-schema`, but we define them manually here so the crate
//! compiles without a live database connection.

use diesel::table;

table! {
    /// Persistent session records.
    sessions (id) {
        id -> Uuid,
        kind -> Text,
        status -> Text,
        workspace_root -> Nullable<Text>,
        channel_ref -> Nullable<Text>,
        requester_session_id -> Nullable<Uuid>,
        latest_turn_id -> Nullable<Uuid>,
        metadata -> Jsonb,
        created_at -> Timestamptz,
        updated_at -> Timestamptz,
        last_activity_at -> Timestamptz,
    }
}

table! {
    /// Individual turns within a session.
    turns (id) {
        id -> Uuid,
        session_id -> Uuid,
        trigger_kind -> Text,
        status -> Text,
        model_ref -> Nullable<Text>,
        started_at -> Timestamptz,
        ended_at -> Nullable<Timestamptz>,
        usage_prompt_tokens -> Nullable<Int4>,
        usage_completion_tokens -> Nullable<Int4>,
    }
}

table! {
    /// Ordered transcript entries.
    transcript_items (id) {
        id -> Uuid,
        session_id -> Uuid,
        turn_id -> Nullable<Uuid>,
        seq -> Int4,
        kind -> Text,
        payload -> Jsonb,
        created_at -> Timestamptz,
    }
}

table! {
    /// Scheduled jobs and cron definitions.
    jobs (id) {
        id -> Uuid,
        job_type -> Text,
        schedule -> Nullable<Text>,
        due_at -> Nullable<Timestamptz>,
        enabled -> Bool,
        last_run_at -> Nullable<Timestamptz>,
        next_run_at -> Nullable<Timestamptz>,
        payload_kind -> Text,
        delivery_mode -> Text,
        payload -> Jsonb,
        created_at -> Timestamptz,
        updated_at -> Timestamptz,
        claimed_at -> Nullable<Timestamptz>,
    }
}

table! {
    /// Approval gates.
    approvals (id) {
        id -> Uuid,
        subject_type -> Text,
        subject_id -> Uuid,
        reason -> Text,
        decision -> Nullable<Text>,
        decided_by -> Nullable<Text>,
        decided_at -> Nullable<Timestamptz>,
        presented_payload -> Jsonb,
        created_at -> Timestamptz,
        handle_ref -> Nullable<Text>,
        host_ref -> Nullable<Text>,
    }
}

table! {
    /// Tool execution audit records.
    tool_executions (id) {
        id -> Uuid,
        tool_call_id -> Uuid,
        session_id -> Uuid,
        turn_id -> Uuid,
        tool_name -> Text,
        arguments -> Jsonb,
        status -> Text,
        result_summary -> Nullable<Text>,
        error_summary -> Nullable<Text>,
        started_at -> Timestamptz,
        ended_at -> Nullable<Timestamptz>,
        approval_id -> Nullable<Uuid>,
        execution_mode -> Nullable<Text>,
    }
}

table! {
    /// Durable background process metadata.
    process_handles (process_id) {
        process_id -> Uuid,
        tool_call_id -> Uuid,
        session_id -> Uuid,
        command -> Text,
        cwd -> Text,
        status -> Text,
        exit_code -> Nullable<Int4>,
        started_at -> Timestamptz,
        ended_at -> Nullable<Timestamptz>,
    }
}

table! {
    /// Outbound channel delivery tracking.
    channel_deliveries (id) {
        id -> Uuid,
        channel -> Text,
        destination -> Text,
        source_session_id -> Nullable<Uuid>,
        message_kind -> Text,
        provider_message_id -> Nullable<Text>,
        attempt_count -> Int4,
        status -> Text,
        sent_at -> Nullable<Timestamptz>,
        created_at -> Timestamptz,
    }
}

table! {
    /// Durable execution history for scheduled jobs.
    job_runs (id) {
        id -> Uuid,
        job_id -> Uuid,
        started_at -> Timestamptz,
        finished_at -> Nullable<Timestamptz>,
        trigger_kind -> Text,
        status -> Text,
        output -> Nullable<Text>,
        created_at -> Timestamptz,
    }
}

table! {
    /// Paired devices with Ed25519 authentication.
    paired_devices (id) {
        id -> Uuid,
        name -> Text,
        public_key -> Text,
        role -> Text,
        scopes -> Jsonb,
        token_hash -> Text,
        token_expires_at -> Timestamptz,
        paired_at -> Timestamptz,
        last_seen_at -> Nullable<Timestamptz>,
        created_at -> Timestamptz,
    }
}

table! {
    /// Pending pairing requests.
    pairing_requests (id) {
        id -> Uuid,
        device_name -> Text,
        public_key -> Text,
        challenge -> Text,
        created_at -> Timestamptz,
        expires_at -> Timestamptz,
    }
}

table! {
    /// Memory embedding chunks for hybrid search.
    memory_embeddings (id) {
        id -> Uuid,
        file_path -> Text,
        chunk_index -> Int4,
        chunk_text -> Text,
        created_at -> Timestamptz,
    }
}

diesel::joinable!(turns -> sessions (session_id));
diesel::joinable!(transcript_items -> sessions (session_id));
diesel::joinable!(tool_executions -> sessions (session_id));
diesel::joinable!(job_runs -> jobs (job_id));
diesel::joinable!(process_handles -> sessions (session_id));

diesel::allow_tables_to_appear_in_same_query!(
    sessions,
    turns,
    transcript_items,
    jobs,
    approvals,
    tool_executions,
    channel_deliveries,
    job_runs,
    paired_devices,
    pairing_requests,
    memory_embeddings,
    process_handles,
);
